# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np 

arr = np.array([np.random.randint(1, 21) for _ in range(25)]) # array of 25 random numbers between 1 and 20
res = np.array(arr).reshape(5, 5)# reshaping array into 5x5
print(res)

[[17 20  7 10 18]
 [ 7 15 15 17 11]
 [12  6 10 16  7]
 [20 11  7 12 11]
 [ 3 19 14 20 16]]


In [2]:

res[:,2:3]=1 # replacing 3rd column with 1
res

array([[17, 20,  1, 10, 18],
       [ 7, 15,  1, 17, 11],
       [12,  6,  1, 16,  7],
       [20, 11,  1, 12, 11],
       [ 3, 19,  1, 20, 16]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr = np.array([i for i in range(1, 17)]).reshape(4,4)# array of 1 to 25

# Replace diagpnal with 0

np.fill_diagonal(arr, 1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  1,  7,  8],
       [ 9, 10,  1, 12],
       [13, 14, 15,  1]])




### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [4]:
arr = np.array(np.random.randint(1, 37, 36)).reshape(6,6)
print(arr)
sub_array = arr[3:6, 2:4] # 3rd and 5th row and 3rd and 4th column
print(sub_array)

[[13 13  3 21 35 23]
 [15 23 14 14  2 19]
 [ 4 30 20 31 33 17]
 [21  3 16 33 36 14]
 [ 7 11 20 22 32 32]
 [ 4 23 33 17 35 21]]
[[16 33]
 [20 22]
 [33 17]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
# Create a NumPy array of shape (5, 5) with random integers
arr = np.random.randint(0, 100, size=(5, 5))

# Extract the elements on the border
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[:, 0], arr[:, -1]))

# Print the border elements
print(border_elements)

[15 46 77 19 99 55 18 19 65  2 15 43 84 28 55 99 78  2 99  2]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
arr1 = np.random.randint(0, 100, size=(3, 4))
arr2 = np.random.randint(0, 100, size=(3, 4))

# Perform element-wise addition
addition = arr1 + arr2
print(addition)
# Perform element-wise subtraction
subtraction = arr1 - arr2
print(subtraction)
# Perform element-wise multiplication
multiplication = arr1 * arr2
print(multiplication)
# Perform element-wise division (note that division by zero will result in an error)
division = arr1 / arr2
print(division)

[[142  36  41  90]
 [151  42  98 138]
 [ 84  68  33 113]]
[[-16  -8   5  58]
 [ 31 -26  66 -16]
 [ 84  54  25  53]]
[[4977  308  414 1184]
 [5460  272 1312 4697]
 [   0  427  116 2490]]
[[0.79746835 0.63636364 1.27777778 4.625     ]
 [1.51666667 0.23529412 5.125      0.79220779]
 [       inf 8.71428571 7.25       2.76666667]]


C:\Users\HP\AppData\Local\Temp\ipykernel_5224\2184046782.py:15: RuntimeWarning: divide by zero encountered in divide
  division = arr1 / arr2





2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
arr = np.arange(1, 17).reshape(4, 4)

# Compute the row-wise sum
row_sum = arr.sum(axis=1)
print(row_sum)      
# Compute the column-wise sum
col_sum = arr.sum(axis=0)
print(col_sum)

[10 26 42 58]
[28 32 36 40]




### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))

# Compute the mean
mean = np.mean(arr)

# Compute the median
median = np.median(arr)

# Compute the standard deviation
std = np.std(arr)

# Compute the variance
variance = np.var(arr)
print(mean, median, std, variance)

69.92 79.0 26.144093023090317 683.5135999999999



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

# Normalize the array
normalized_arr = (arr - np.mean(arr)) / np.std(arr)

print(normalized_arr)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]




### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
# Create a NumPy array of shape (3, 3) filled with random integers
arr = np.random.randint(0, 100, size=(3, 3))
print(arr, '\n')
# Create a 1D array of shape (3,) filled with random integers
vector = np.random.randint(0, 100, size=(3,))
print(vector, '\n')
# Add the 1D array to each row of the 2D array using broadcasting
result = arr + vector[:, np.newaxis]

print(result)

[[79 29 99]
 [ 8 33 74]
 [19 48 92]] 

[ 4 91 99] 

[[ 83  33 103]
 [ 99 124 165]
 [118 147 191]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
# Create a NumPy array of shape (4, 4) filled with random integers
arr = np.random.randint(0, 100, size=(4, 4))
print(arr, '\n')
# Create a 1D array of shape (4,) filled with random integers
vector = np.random.randint(0, 100, size=(4,))
print(vector, '\n')
# Subtract the 1D array from each column of the 2D array using broadcasting
result = arr - vector[:, np.newaxis]

print(result)

[[53 51 65 31]
 [89 24 20 34]
 [27 63 18 67]
 [30  8 42 42]] 

[ 9 58 40  0] 

[[ 44  42  56  22]
 [ 31 -34 -38 -24]
 [-13  23 -22  27]
 [ 30   8  42  42]]





### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
# Create a random 3x3 matrix
matrix = np.random.randint(1, 10, size=(3, 3))
print("Matrix:\n", matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)

# Compute the eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[5 5 8]
 [4 1 8]
 [8 3 6]]
Determinant: 141.9999999999999
Inverse:
 [[-0.12676056 -0.04225352  0.22535211]
 [ 0.28169014 -0.23943662 -0.05633803]
 [ 0.02816901  0.17605634 -0.1056338 ]]
Eigenvalues: [16.56283169+0.j         -2.28141584+1.83536235j -2.28141584-1.83536235j]
Eigenvectors:
 [[ 0.63016198+0.j          0.11769296+0.47561645j  0.11769296-0.47561645j]
 [ 0.47693357+0.j         -0.73265431+0.j         -0.73265431-0.j        ]
 [ 0.61272363+0.j          0.24167145-0.40589399j  0.24167145+0.40589399j]]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
# Create a NumPy array of shape (2, 3)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a NumPy array of shape (3, 2)
arr2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result = arr1 @ arr2
print(result)

[[ 58  64]
 [139 154]]





### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr, '\n')
# Reshape the array to shape (1, 9)
reshaped_arr1 = arr.reshape(1, 9)
print(reshaped_arr1, '\n')
# Reshape the array to shape (9, 1)
reshaped_arr2 = arr.reshape(9, 1)
print(reshaped_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3 4 5 6 7 8 9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))
print(arr, '\n')
# Flatten the array
flattened_arr = arr.flatten()
print(flattened_arr, '\n')
# Reshape the flattened array back to (5, 5)
reshaped_arr = flattened_arr.reshape(5, 5)
print(reshaped_arr)

[[92 87 26 45 30]
 [61 97 88 83  0]
 [40 52 11 63 33]
 [13 68 98 53 69]
 [22 24 88 33 97]] 

[92 87 26 45 30 61 97 88 83  0 40 52 11 63 33 13 68 98 53 69 22 24 88 33
 97] 

[[92 87 26 45 30]
 [61 97 88 83  0]
 [40 52 11 63 33]
 [13 68 98 53 69]
 [22 24 88 33 97]]




### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [16]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))
print(arr, '\n')
# Define the indices of the corners
indices = np.array([[0, 0], [0, -1], [-1, 0], [-1, -1]])
print(indices, '\n')
# Extract the elements at the corners using fancy indexing
corner_elements = arr[indices]
print(corner_elements)

[[74 90 58 33 10]
 [50 92 89 78 22]
 [84 90 93  9 18]
 [81 69 93 68 26]
 [15 20 61 30 12]] 

[[ 0  0]
 [ 0 -1]
 [-1  0]
 [-1 -1]] 

[[[74 90 58 33 10]
  [74 90 58 33 10]]

 [[74 90 58 33 10]
  [15 20 61 30 12]]

 [[15 20 61 30 12]
  [74 90 58 33 10]]

 [[15 20 61 30 12]
  [15 20 61 30 12]]]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
# Create a NumPy array of shape (4, 4) filled with random integers
arr = np.random.randint(0, 100, size=(4, 4))
print(arr, '\n')
# Create a boolean mask to identify elements greater than 10
mask = arr > 10
print(mask, '\n')
# Set the elements greater than 10 to 10 using boolean indexing
arr[mask] = 10
print(arr)

[[39 31 62 71]
 [17 46 35 26]
 [97 91 35  3]
 [93 14 99 60]] 

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True False]
 [ True  True  True  True]] 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10  3]
 [10 10 10 10]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [18]:
# Define the dtype for the structured array
dtype = np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f4')])
print(dtype, '\n')
# Create the structured array
arr = np.array([('Alice', 25, 55.5), ('Bob', 30, 70.0), ('Charlie', 20, 50.0)], dtype=dtype)
print(arr, '\n')
# Sort the array by age
arr = arr[arr['age'].argsort()]
print(arr, '\n')
# Print the sorted array
print(arr)

[('name', 'S10'), ('age', '<i4'), ('weight', '<f4')] 

[(b'Alice', 25, 55.5) (b'Bob', 30, 70. ) (b'Charlie', 20, 50. )] 

[(b'Charlie', 20, 50. ) (b'Alice', 25, 55.5) (b'Bob', 30, 70. )] 

[(b'Charlie', 20, 50. ) (b'Alice', 25, 55.5) (b'Bob', 30, 70. )]




2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [19]:
# Create a structured array with fields 'x' and 'y' (both integers)
data_type = [('x', int), ('y', int)]
points = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)

# Extract x and y coordinates as separate NumPy arrays
x_coords = points['x']
y_coords = points['y']

# Create a 2D array of coordinates
coords = np.column_stack((x_coords, y_coords))

# Function to calculate Euclidean distance
def euclidean_distance(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

# Compute distances between all pairs of points
num_points = len(coords)
distances = np.zeros((num_points, num_points))

for i in range(num_points):
    for j in range(i+1, num_points):  # Avoid redundant calculations
        distances[i, j] = euclidean_distance(coords[i], coords[j])
        distances[j, i] = distances[i, j]  # Symmetric matrix

print(distances)



[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]




### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [20]:
# Create a masked array of shape (4, 4) with random integers
arr = np.ma.array(np.random.randint(0, 100, size=(4, 4)), mask=np.random.randint(0, 2, size=(4, 4)) > 0)

# Mask the elements greater than 10
arr[arr > 10] = np.ma.masked

# Compute the sum of the unmasked elements
sum_unmasked = np.ma.sum(arr)

# Print the sum of the unmasked elements
print(sum_unmasked)

--



2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [21]:
# Create a masked array of shape (3, 3) with random integers
arr = np.ma.array(np.random.randint(0, 100, size=(3, 3)))

# Mask the diagonal elements
arr.mask = np.eye(3, dtype=bool)

# Compute the mean of the unmasked elements
mean = np.ma.mean(arr)

# Replace the masked elements with the mean
arr[arr.mask] = mean

# Print the updated array
print(arr)

[[46 81 9]
 [42 46 9]
 [41 98 46]]
