# Module: NumPy Assignments
## Lesson: NumPy


### Assignment 1: Array Creation and Manipulation

1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [1]:
import numpy as np 

arr = np.array([np.random.randint(1, 21) for _ in range(25)]) # array of 25 random numbers between 1 and 20
res = np.array(arr).reshape(5, 5)# reshaping array into 5x5
print(res)

[[ 8 13  2  4 18]
 [ 2 18 20 12 15]
 [10 11  2 20  6]
 [ 6 13 17 11  1]
 [16  6 14  7 10]]


In [2]:

res[:,2:3]=1 # replacing 3rd column with 1
res

array([[ 8, 13,  1,  4, 18],
       [ 2, 18,  1, 12, 15],
       [10, 11,  1, 20,  6],
       [ 6, 13,  1, 11,  1],
       [16,  6,  1,  7, 10]])

2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [3]:
arr = np.array([i for i in range(1, 17)]).reshape(4,4)# array of 1 to 25

# Replace diagpnal with 0

np.fill_diagonal(arr, 1)
arr

array([[ 1,  2,  3,  4],
       [ 5,  1,  7,  8],
       [ 9, 10,  1, 12],
       [13, 14, 15,  1]])




### Assignment 2: Array Indexing and Slicing

1. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.


In [4]:
arr = np.array(np.random.randint(1, 37, 36)).reshape(6,6)
print(arr)
sub_array = arr[3:6, 2:4] # 3rd and 5th row and 3rd and 4th column
print(sub_array)

[[12 35 19 36  5 11]
 [16 34 29 34 34 22]
 [32 24 32 26 36 30]
 [36 33 27 27 17  9]
 [11 35  8 16 32 22]
 [23  6 35 15 19 10]]
[[27 27]
 [ 8 16]
 [35 15]]


2. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [5]:
# Create a NumPy array of shape (5, 5) with random integers
arr = np.random.randint(0, 100, size=(5, 5))

# Extract the elements on the border
border_elements = np.concatenate((arr[0, :], arr[-1, :], arr[:, 0], arr[:, -1]))

# Print the border elements
print(border_elements)

[93 80  7 14 11 32 96 47 71 77 93 35 21  4 32 11 68 67 69 77]


### Assignment 3: Array Operations

1. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [6]:
# Create two NumPy arrays of shape (3, 4) filled with random integers
arr1 = np.random.randint(0, 100, size=(3, 4))
arr2 = np.random.randint(0, 100, size=(3, 4))

# Perform element-wise addition
addition = arr1 + arr2
print(addition)
# Perform element-wise subtraction
subtraction = arr1 - arr2
print(subtraction)
# Perform element-wise multiplication
multiplication = arr1 * arr2
print(multiplication)
# Perform element-wise division (note that division by zero will result in an error)
division = arr1 / arr2
print(division)

[[112  85 107 107]
 [ 85 100 182 114]
 [ 43  70  74  63]]
[[ 68  -3  85   3]
 [-71  58  -2  14]
 [ 37  34 -72  19]]
[[1980 1804 1056 2860]
 [ 546 1659 8280 3200]
 [ 120  936   73  902]]
[[ 4.09090909  0.93181818  8.72727273  1.05769231]
 [ 0.08974359  3.76190476  0.97826087  1.28      ]
 [13.33333333  2.88888889  0.01369863  1.86363636]]





2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [7]:
# Create a NumPy array of shape (4, 4) with values from 1 to 16
arr = np.arange(1, 17).reshape(4, 4)

# Compute the row-wise sum
row_sum = arr.sum(axis=1)
print(row_sum)      
# Compute the column-wise sum
col_sum = arr.sum(axis=0)
print(col_sum)

[10 26 42 58]
[28 32 36 40]




### Assignment 4: Statistical Operations

1. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [8]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))

# Compute the mean
mean = np.mean(arr)

# Compute the median
median = np.median(arr)

# Compute the standard deviation
std = np.std(arr)

# Compute the variance
variance = np.var(arr)
print(mean, median, std, variance)

40.6 30.0 29.50254226333724 870.4000000000001



2. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [9]:
# Create a NumPy array of shape (3, 3) with values from 1 to 9
arr = np.arange(1, 10).reshape(3, 3)

# Normalize the array
normalized_arr = (arr - np.mean(arr)) / np.std(arr)

print(normalized_arr)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]




### Assignment 5: Broadcasting

1. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [10]:
# Create a NumPy array of shape (3, 3) filled with random integers
arr = np.random.randint(0, 100, size=(3, 3))
print(arr, '\n')
# Create a 1D array of shape (3,) filled with random integers
vector = np.random.randint(0, 100, size=(3,))
print(vector, '\n')
# Add the 1D array to each row of the 2D array using broadcasting
result = arr + vector[:, np.newaxis]

print(result)

[[86 40 94]
 [29 20 98]
 [47 58 96]] 

[22  6  2] 

[[108  62 116]
 [ 35  26 104]
 [ 49  60  98]]


2. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
# Create a NumPy array of shape (4, 4) filled with random integers
arr = np.random.randint(0, 100, size=(4, 4))
print(arr, '\n')
# Create a 1D array of shape (4,) filled with random integers
vector = np.random.randint(0, 100, size=(4,))
print(vector, '\n')
# Subtract the 1D array from each column of the 2D array using broadcasting
result = arr - vector[:, np.newaxis]

print(result)

[[84 42 80 45]
 [43 48 23  3]
 [80 62 58 26]
 [ 6 33 71 75]] 

[18 32 78 12] 

[[ 66  24  62  27]
 [ 11  16  -9 -29]
 [  2 -16 -20 -52]
 [ -6  21  59  63]]





### Assignment 6: Linear Algebra

1. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [12]:
# Create a random 3x3 matrix
matrix = np.random.randint(1, 10, size=(3, 3))
print("Matrix:\n", matrix)

# Compute the determinant
determinant = np.linalg.det(matrix)
print("Determinant:", determinant)

# Compute the inverse
inverse = np.linalg.inv(matrix)
print("Inverse:\n", inverse)

# Compute the eigenvalues
eigenvalues, eigenvectors = np.linalg.eig(matrix)
print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)


Matrix:
 [[4 8 1]
 [1 8 3]
 [8 4 1]]
Determinant: 108.00000000000003
Inverse:
 [[-0.03703704 -0.03703704  0.14814815]
 [ 0.21296296 -0.03703704 -0.10185185]
 [-0.55555556  0.44444444  0.22222222]]
Eigenvalues: [ 0.29401945+2.9351042j  0.29401945-2.9351042j 12.41196111+0.j       ]
Eigenvectors:
 [[ 0.06531861+0.39399235j  0.06531861-0.39399235j -0.58695106+0.j        ]
 [-0.2820348 -0.15855138j -0.2820348 +0.15855138j -0.54199636+0.j        ]
 [ 0.85780029+0.j          0.85780029-0.j         -0.6014386 +0.j        ]]


2. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [13]:
# Create a NumPy array of shape (2, 3)
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

# Create a NumPy array of shape (3, 2)
arr2 = np.array([[7, 8], [9, 10], [11, 12]])

# Perform matrix multiplication
result = arr1 @ arr2
print(result)

[[ 58  64]
 [139 154]]





### Assignment 7: Advanced Array Manipulation

1. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [14]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr, '\n')
# Reshape the array to shape (1, 9)
reshaped_arr1 = arr.reshape(1, 9)
print(reshaped_arr1, '\n')
# Reshape the array to shape (9, 1)
reshaped_arr2 = arr.reshape(9, 1)
print(reshaped_arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[1 2 3 4 5 6 7 8 9]] 

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]



2. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [15]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))
print(arr, '\n')
# Flatten the array
flattened_arr = arr.flatten()
print(flattened_arr, '\n')
# Reshape the flattened array back to (5, 5)
reshaped_arr = flattened_arr.reshape(5, 5)
print(reshaped_arr)

[[56 64  7 77 29]
 [62 87 63 56 65]
 [47 96  5 58 10]
 [14  0 32  0 57]
 [15 34 74  6 57]] 

[56 64  7 77 29 62 87 63 56 65 47 96  5 58 10 14  0 32  0 57 15 34 74  6
 57] 

[[56 64  7 77 29]
 [62 87 63 56 65]
 [47 96  5 58 10]
 [14  0 32  0 57]
 [15 34 74  6 57]]




### Assignment 8: Fancy Indexing and Boolean Indexing

1. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [16]:
# Create a NumPy array of shape (5, 5) filled with random integers
arr = np.random.randint(0, 100, size=(5, 5))
print(arr, '\n')
# Define the indices of the corners
indices = np.array([[0, 0], [0, -1], [-1, 0], [-1, -1]])
print(indices, '\n')
# Extract the elements at the corners using fancy indexing
corner_elements = arr[indices]
print(corner_elements)

[[82 83  6 69  0]
 [86 55 10 38 94]
 [46 45 44 14 65]
 [92 33 61 21 68]
 [52 38 20 57 64]] 

[[ 0  0]
 [ 0 -1]
 [-1  0]
 [-1 -1]] 

[[[82 83  6 69  0]
  [82 83  6 69  0]]

 [[82 83  6 69  0]
  [52 38 20 57 64]]

 [[52 38 20 57 64]
  [82 83  6 69  0]]

 [[52 38 20 57 64]
  [52 38 20 57 64]]]



2. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [17]:
# Create a NumPy array of shape (4, 4) filled with random integers
arr = np.random.randint(0, 100, size=(4, 4))
print(arr, '\n')
# Create a boolean mask to identify elements greater than 10
mask = arr > 10
print(mask, '\n')
# Set the elements greater than 10 to 10 using boolean indexing
arr[mask] = 10
print(arr)

[[94 92 81 10]
 [45 30 28 17]
 [38 91 47 72]
 [75 93 94 95]] 

[[ True  True  True False]
 [ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]] 

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]



### Assignment 9: Structured Arrays

1. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [18]:
# Define the dtype for the structured array
dtype = np.dtype([('name', 'S10'), ('age', 'i4'), ('weight', 'f4')])
print(dtype, '\n')
# Create the structured array
arr = np.array([('Alice', 25, 55.5), ('Bob', 30, 70.0), ('Charlie', 20, 50.0)], dtype=dtype)
print(arr, '\n')
# Sort the array by age
arr = arr[arr['age'].argsort()]
print(arr, '\n')
# Print the sorted array
print(arr)

[('name', 'S10'), ('age', '<i4'), ('weight', '<f4')] 

[(b'Alice', 25, 55.5) (b'Bob', 30, 70. ) (b'Charlie', 20, 50. )] 

[(b'Charlie', 20, 50. ) (b'Alice', 25, 55.5) (b'Bob', 30, 70. )] 

[(b'Charlie', 20, 50. ) (b'Alice', 25, 55.5) (b'Bob', 30, 70. )]




2. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [19]:
# Create a structured array with fields 'x' and 'y' (both integers)
data_type = [('x', int), ('y', int)]
points = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)

# Extract x and y coordinates as separate NumPy arrays
x_coords = points['x']
y_coords = points['y']

# Create a 2D array of coordinates
coords = np.column_stack((x_coords, y_coords))

# Function to calculate Euclidean distance
def euclidean_distance(p1, p2):
    return np.sqrt(np.sum((p1 - p2)**2))

# Compute distances between all pairs of points
num_points = len(coords)
distances = np.zeros((num_points, num_points))

for i in range(num_points):
    for j in range(i+1, num_points):  # Avoid redundant calculations
        distances[i, j] = euclidean_distance(coords[i], coords[j])
        distances[j, i] = distances[i, j]  # Symmetric matrix

print(distances)



[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]




### Assignment 10: Masked Arrays

1. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [20]:
# Create a masked array of shape (4, 4) with random integers
arr = np.ma.array(np.random.randint(0, 100, size=(4, 4)), mask=np.random.randint(0, 2, size=(4, 4)) > 0)

# Mask the elements greater than 10
arr[arr > 10] = np.ma.masked

# Compute the sum of the unmasked elements
sum_unmasked = np.ma.sum(arr)

# Print the sum of the unmasked elements
print(sum_unmasked)

1



2. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [21]:
# Create a masked array of shape (3, 3) with random integers
arr = np.ma.array(np.random.randint(0, 100, size=(3, 3)))

# Mask the diagonal elements
arr.mask = np.eye(3, dtype=bool)

# Compute the mean of the unmasked elements
mean = np.ma.mean(arr)

# Replace the masked elements with the mean
arr[arr.mask] = mean

# Print the updated array
print(arr)

[[85 88 82]
 [87 85 97]
 [82 77 85]]
