# Module 3: Data Structures Assignments
## Lesson 3.1: Lists

### Assignment 1: Creating and Accessing Lists

Create a list of the first 20 positive integers. Print the list.

In [30]:
positive_list = [i for i in range(1,21)]
print(positive_list)
print(len(positive_list))

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]
20


### Assignment 2: Accessing List Elements

Print the first, middle, and last elements of the list created in Assignment 1.

In [31]:
first_element: int = positive_list[0]
middle_element: int = positive_list[len(positive_list)//2:len(positive_list)//2+1][0] #// for integer division
last_element: int = positive_list[-1]
print(first_element)
print(middle_element)
print(last_element)

1
11
20


### Assignment 3: List Slicing

Print the first five elements, the last five elements, and the elements from index 5 to 15 of the list created in Assignment 1.


In [32]:
print('first 5 elements:', positive_list[:5])
print('last 5 elements:', positive_list[-5:])
print('list from 5th to 10th element:', positive_list[4:10])

first 5 elements: [1, 2, 3, 4, 5]
last 5 elements: [16, 17, 18, 19, 20]
list from 5th to 10th element: [5, 6, 7, 8, 9, 10]


### Assignment 4: List Comprehensions

Create a new list containing the squares of the first 10 positive integers using a list comprehension. Print the new list.

In [33]:
list_positive = [i**2 for i in range(1,11)]
print('square of first 10 natural numbers:', list_positive)

square of first 10 natural numbers: [1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


### Assignment 5: Filtering Lists

Create a new list containing only the even numbers from the list created in Assignment 1 using a list comprehension. Print the new list.

In [34]:
positive_even_list:list = [i for i in positive_list if i%2==0]
print(positive_even_list)

[2, 4, 6, 8, 10, 12, 14, 16, 18, 20]


### Assignment 6: List Methods

Create a list of random numbers and sort it in ascending and descending order. Remove the duplicates from the list and print the modified list.

In [35]:
import random
new_random_list = [random.randint(1,100) for i in range(10)]
list_with_duplicates = new_random_list+ new_random_list[1:5]# adding for create duplicate
print('random list',list_with_duplicates) 
sorted_list = sorted(list_with_duplicates)
print('sorted list',sorted_list)
no_duplicate_list = list(dict.fromkeys(sorted_list))    
print('no duplicate list',no_duplicate_list)


random list [36, 81, 72, 12, 36, 83, 83, 43, 18, 82, 81, 72, 12, 36]
sorted list [12, 12, 18, 36, 36, 36, 43, 72, 72, 81, 81, 82, 83, 83]
no duplicate list [12, 18, 36, 43, 72, 81, 82, 83]



### Assignment 7: Nested Lists

Create a nested list representing a 3x3 matrix and print the matrix. Access and print the element at the second row and third column.

In [36]:
nested_list = []
for i in range(3):
    nested_list.append([])
    for j in range(3):
        nested_list[i].append(random.randint(1,100))
print(nested_list)
print('second row third column ::  ',nested_list[1][2])

[[30, 39, 1], [74, 15, 80], [61, 98, 34]]
second row third column ::   80


### Assignment 8: List of Dictionaries

Create a list of dictionaries where each dictionary represents a student with keys 'name' and 'score'. Sort the list of dictionaries by the 'score' in descending order and print the sorted list.

In [37]:
student_name_list:list = ['Rohan', 'Subhas', 'Raj', 'Rishabh', 'Raju', 'Rohit']
student_name_score:list = [random.randint(1,100) for i in range(len(student_name_list))]
student_combine_list:list = []
for i in range(len(student_name_list)):
    student_combine_list.append([student_name_list[i],student_name_score[i]])
print(student_combine_list)

[['Rohan', 47], ['Subhas', 71], ['Raj', 11], ['Rishabh', 3], ['Raju', 15], ['Rohit', 28]]



### Assignment 9: Matrix Transposition

Write a function that takes a 3x3 matrix (nested list) as input and returns its transpose. Print the original and transposed matrices.

In [38]:
def transpose_matrix(matrix):
    transposed = [[row[i] for row in matrix] for i in range(3)]
    print("Original matrix:")
    for row in matrix:
        print(row)
    print("Transposed matrix:")
    for row in transposed:
        print(row)
    return transposed

# Example usage
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transposed = transpose_matrix(matrix)

Original matrix:
[1, 2, 3]
[4, 5, 6]
[7, 8, 9]
Transposed matrix:
[1, 4, 7]
[2, 5, 8]
[3, 6, 9]


In [39]:
import numpy as np

def transpose_matrix(matrix):
    matrix = np.array(matrix)
    transposed = matrix.T
    print("Original matrix:")
    print(matrix)
    print("Transposed matrix:")
    print(transposed)
    return transposed

# Example usage
matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
transposed = transpose_matrix(matrix)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed matrix:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


### Assignment 10: Flattening a Nested List

Write a function that takes a nested list and flattens it into a single list. Print the original and flattened lists.

In [40]:
def flatten_list(nested_list):
    flattened_list = []
    for i in nested_list:
        if isinstance(i, list):
            flattened_list.extend(flatten_list(i))
        else:
            flattened_list.append(i)
    return flattened_list

nested_list = [[1, 2, [3, 4]], [5, 6], 7, [8, [9, 10]]]
print("Original nested list:", nested_list)
flattened_list = flatten_list(nested_list)
print("Flattened list:", flattened_list)

Original nested list: [[1, 2, [3, 4]], [5, 6], 7, [8, [9, 10]]]
Flattened list: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [44]:
class NumericList(list):
  def __init__(self):
    pass

num_list = NumericList()

# Check if num_list is an instance of NumericList
print(isinstance(num_list, NumericList))  # True

# Check if num_list is a kind of list (because NumericList inherits from list)
print(isinstance(num_list, list))  # True

# Check if a string is a string
print(isinstance("hello", str))  # True

# Check if a variable can be either a string or a list
data = "hello"
print(isinstance(data, (str, list)))  # True


True
True
True
True


### Assignment 11: List Manipulation

Create a list of the first 10 positive integers. Remove the elements at indices 2, 4, and 6, and insert the element '99' at index 5. Print the modified list.

In [48]:

# Create a list of the first 10 positive integers
original_list = list(range(1, 11))

# Remove the elements at indices 2, 4, and 6
indices_to_remove = [2, 4, 6]
for index in sorted(indices_to_remove, reverse=True):
    original_list.pop(index)

# Insert the element '99' at index 5
original_list.insert(5, 99)

# Print the modified list
print("Modified list:", original_list)



Modified list: [1, 2, 4, 6, 8, 99, 9, 10]


### Assignment 12: List Zipping

Create two lists of the same length. Use the `zip` function to combine these lists into a list of tuples and print the result.

In [50]:
first_list:list = [1, 2, 3, 4, 5]
second_list:list = [6, 7, 8, 9, 10]
zipped_list = list(zip(first_list, second_list))
print(zipped_list)

[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]


### Assignment 13: List Reversal

Write a function that takes a list and returns a new list with the elements in reverse order. Print the original and reversed lists.

In [52]:
def list_revalsal(list1):
    return list1[::-1]
reversed_list = list_revalsal([1,2,7,4])
print(reversed_list)

[4, 7, 2, 1]



### Assignment 14: List Rotation

Write a function that rotates a list by n positions. Print the original and rotated lists.

In [53]:
def rotate_list(input_list, n):
    n = n % len(input_list)  # Ensure n is within the length of the list
    rotated_list = input_list[n:] + input_list[:n]
    return rotated_list

# Original list
original_list = [1, 2, 3, 4, 5, 6, 7]

# Rotate the list by 2 positions
n = 2
rotated_list = rotate_list(original_list, n)

print("Original list:", original_list)
print(f"Rotated list by {n} positions:", rotated_list)

Original list: [1, 2, 3, 4, 5, 6, 7]
Rotated list by 2 positions: [3, 4, 5, 6, 7, 1, 2]


### Assignment 15: List Intersection

Write a function that takes two lists and returns a new list containing only the elements that are present in both lists. Print the intersected list.

In [54]:
def intersection(list1, list2):
    intersected_list = list(set(list1) & set(list2))
    return intersected_list

# Two lists
list1 = [1, 2, 3, 4, 5]
list2 = [3, 4, 5, 6, 7]

# Find elements present in both lists
intersected_list = intersection(list1, list2)

print("Intersected list:", intersected_list)

Intersected list: [3, 4, 5]
